/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import  {useFrame} from "@react-three/fiber";
import  {useGLTF}  from "@react-three/drei";
import { Mesh } from "three";

export default function Model(props: any) {
	const group = useRef<Mesh>(null!);
	useFrame(() => {
		group.current.rotation.z -= 0.001;
		group.current.rotation.x -= 0.001;

		group.current.rotation.y -= 0.001;
	});
	// @ts-ignore
	const { nodes, materials } = useGLTF("/assets/untitled.gltf");
	return (
		<group {...props} dispose={null}>
			<mesh
				ref={group}
				castShadow
				receiveShadow
				geometry={nodes.uploads_files_665421_Pepe.geometry}
				material={materials["Default OBJ"]}
				rotation={[-Math.PI / 10, 0, 0]}
				scale={[0.3, 0.3, 0.3]}
			/>
		</group>
	);
}

useGLTF.preload("/assets/untitled.gltf");
